/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated.datasets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAnalisesRouteImport } from './routes/_authenticated.analises'
import { Route as AuthenticatedAgendamentosRouteImport } from './routes/_authenticated.agendamentos'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated.administracao'
import { Route as AuthenticatedPedidosNovoRouteImport } from './routes/_authenticated.pedidos.novo'
import { Route as AuthenticatedAgendamentosReservarRouteImport } from './routes/_authenticated.agendamentos_.reservar'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalisesRoute = AuthenticatedAnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendamentosRoute =
  AuthenticatedAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosNovoRoute =
  AuthenticatedPedidosNovoRouteImport.update({
    id: '/pedidos/novo',
    path: '/pedidos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendamentosReservarRoute =
  AuthenticatedAgendamentosReservarRouteImport.update({
    id: '/agendamentos_/reservar',
    path: '/agendamentos/reservar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/analises': typeof AuthenticatedAnalisesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/agendamentos/reservar': typeof AuthenticatedAgendamentosReservarRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/analises': typeof AuthenticatedAnalisesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/agendamentos/reservar': typeof AuthenticatedAgendamentosReservarRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/_authenticated/analises': typeof AuthenticatedAnalisesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/agendamentos_/reservar': typeof AuthenticatedAgendamentosReservarRoute
  '/_authenticated/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/administracao'
    | '/agendamentos'
    | '/analises'
    | '/dashboard'
    | '/datasets'
    | '/agendamentos/reservar'
    | '/pedidos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/administracao'
    | '/agendamentos'
    | '/analises'
    | '/dashboard'
    | '/datasets'
    | '/agendamentos/reservar'
    | '/pedidos/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/home'
    | '/_authenticated/administracao'
    | '/_authenticated/agendamentos'
    | '/_authenticated/analises'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/agendamentos_/reservar'
    | '/_authenticated/pedidos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analises': {
      id: '/_authenticated/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AuthenticatedAnalisesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agendamentos': {
      id: '/_authenticated/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AuthenticatedAgendamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/novo': {
      id: '/_authenticated/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AuthenticatedPedidosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agendamentos_/reservar': {
      id: '/_authenticated/agendamentos_/reservar'
      path: '/agendamentos/reservar'
      fullPath: '/agendamentos/reservar'
      preLoaderRoute: typeof AuthenticatedAgendamentosReservarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedAgendamentosRoute: typeof AuthenticatedAgendamentosRoute
  AuthenticatedAnalisesRoute: typeof AuthenticatedAnalisesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedAgendamentosReservarRoute: typeof AuthenticatedAgendamentosReservarRoute
  AuthenticatedPedidosNovoRoute: typeof AuthenticatedPedidosNovoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedAgendamentosRoute: AuthenticatedAgendamentosRoute,
  AuthenticatedAnalisesRoute: AuthenticatedAnalisesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedAgendamentosReservarRoute:
    AuthenticatedAgendamentosReservarRoute,
  AuthenticatedPedidosNovoRoute: AuthenticatedPedidosNovoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
